name: Remove new issue label

on:
  issues:
    types: [assigned]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove new issue label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: status: new issue
